<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Inertia\Inertia;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class ProfileController extends Controller
{

    public function index(Request $request)
    {
        $limit = $request->query('limit', 10);
        $userQuery = \App\Models\User::query();
        if (!auth()->user()->is_admin) {
            $tenantId = auth()->user()->tenant_id ?: auth()->id();
            $userQuery->where('tenant_id', $tenantId);
        }
        $users = $userQuery->paginate($limit, ['*'], 'users_page');

        $activityLogs = \App\Models\ActivityLog::with('user:id,name,email,profile_logo')->latest()->paginate($limit, ['*'], 'activity_page');

        $backupDir = storage_path('app/backups');
        $backups = [];
        if (File::exists($backupDir)) {
            $files = File::files($backupDir);
            foreach ($files as $file) {
                if ($file->getExtension() === 'sql') {
                    $backups[] = [
                        'id' => $file->getFilename(),
                        'name' => 'Database Backup - ' . date('Y-m-d H:i:s', $file->getMTime()),
                        'size' => number_format($file->getSize() / 1048576, 2) . ' MB',
                        'date' => date('Y-m-d H:i:s', $file->getMTime()),
                    ];
                }
            }
            usort($backups, function ($a, $b) {
                return $b['date'] <=> $a['date'];
            });
        }

        $tenantId = auth()->user()->tenant_id ?: auth()->id();
        $fields = \App\Models\TenantFieldOption::where('tenant_id', $tenantId)->get()->groupBy('field_name');

        $getDefault = function ($key, $defaults) use ($fields) {
            return isset($fields[$key]) ? $fields[$key]->pluck('option_value')->toArray() : $defaults;
        };

        $fieldOptions = [
            'biz_type' => $getDefault('biz_type', ['Residential', 'Commercial']),
            'source' => $getDefault('source', ['Own Lead', 'Social Media']),
            'division' => $getDefault('division', ['Yangon', 'Mandalay']),
            'township' => $getDefault('township', ['Bahan', 'Sanchaung']),
            'product' => $getDefault('product', ['Internet']),
            'channel' => $getDefault('channel', ['Direct', 'Partner']),
            'package' => $getDefault('package', ['Home Plus', 'Business DIA']),
        ];

        return Inertia::render('Settings', [
            'users' => $users,
            'activityLogs' => $activityLogs,
            'backups' => $backups,
            'fieldOptions' => $fieldOptions,
            'plans' => \App\Models\Plan::all(),
            'limit' => $limit,
            'tab' => $request->query('tab', 'profile')
        ]);
    }


    public function update(Request $request)
    {
        $user = $request->user();

        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,' . $user->id,
            'password' => 'nullable|string|min:8|confirmed',
            'profile_logo' => 'nullable|image|mimes:jpeg,png,jpg,gif|max:2048'
        ]);

        $oldData = [
            'name' => $user->name,
            'email' => $user->email,
        ];

        $user->name = $request->name;
        $user->email = $request->email;

        if ($request->filled('password')) {
            $user->password = Hash::make($request->password);
        }

        if ($request->hasFile('profile_logo')) {
            if ($user->profile_logo && Storage::disk('public')->exists($user->profile_logo)) {
                Storage::disk('public')->delete($user->profile_logo);
            }

            $path = $request->file('profile_logo')->store('profile_logos', 'public');
            $user->profile_logo = $path;
        }

        $user->save();

        return redirect()->back()->with('success', 'Settings updated successfully.');
    }

    private function generateSqlDump($filePath)
    {
        $tables = \Illuminate\Support\Facades\DB::select('SHOW TABLES');
        $tables = array_map('current', json_decode(json_encode($tables), true));

        $sql = "-- Database Dump Generated by Pipeline\n";
        $sql .= "-- Generated at: " . date('Y-m-d H:i:s') . "\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS=0;\n\n";

        foreach ($tables as $table) {
            $sql .= "-- Table structure for `$table`\n";
            $sql .= "DROP TABLE IF EXISTS `$table`;\n";

            $createTableObj = \Illuminate\Support\Facades\DB::select("SHOW CREATE TABLE `$table`")[0];
            $createTableProp = 'Create Table';
            if (isset($createTableObj->{ 'Create View'})) {
                $createTableProp = 'Create View';
            }
            $sql .= $createTableObj->$createTableProp . ";\n\n";

            if ($createTableProp === 'Create Table') {
                $rows = \Illuminate\Support\Facades\DB::table($table)->get();
                if ($rows->count() > 0) {
                    $sql .= "-- Data for `$table`\n";
                    foreach ($rows as $row) {
                        $insertKeys = "`" . implode("`, `", array_keys((array)$row)) . "`";
                        $insertValues = array_map(function ($val) {
                            if (is_null($val))
                                return "NULL";
                            return "'" . addslashes((string)$val) . "'";
                        }, (array)$row);

                        $sql .= "INSERT INTO `$table` ($insertKeys) VALUES (" . implode(", ", $insertValues) . ");\n";
                    }
                    $sql .= "\n\n";
                }
            }
        }

        $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
        File::put($filePath, $sql);
    }

    public function createBackup()
    {
        if (!auth()->user()->is_admin && !auth()->user()->hasPermissionTo('setting_backup')) {
            abort(403, 'Unauthorized action.');
        }

        $backupDir = storage_path('app/backups');
        if (!File::exists($backupDir)) {
            File::makeDirectory($backupDir, 0755, true);
        }

        $filename = "backup-" . date('Y-m-d-H-i-s') . ".sql";
        $path = $backupDir . '/' . $filename;

        $this->generateSqlDump($path);

        \App\Models\ActivityLog::create([
            'user_id' => auth()->id(),
            'action' => 'backup_created',
            'description' => "Created database backup $filename",
            'ip_address' => request()->ip(),
            'user_agent' => request()->userAgent(),
        ]);

        return redirect()->back()->with('success', 'Backup generated successfully.');
    }

    public function downloadBackup($id)
    {
        if (!auth()->user()->is_admin && !auth()->user()->hasPermissionTo('setting_backup')) {
            abort(403, 'Unauthorized action.');
        }

        $path = storage_path('app/backups/' . $id);
        if (\File::exists($path)) {
            return response()->download($path);
        }
        return redirect()->back()->withErrors('Backup file not found.');
    }

    public function deleteBackup($id)
    {
        if (!auth()->user()->is_admin && !auth()->user()->hasPermissionTo('setting_backup')) {
            abort(403, 'Unauthorized action.');
        }

        $path = storage_path('app/backups/' . $id);
        if (File::exists($path)) {
            File::delete($path);

            \App\Models\ActivityLog::create([
                'user_id' => auth()->id(),
                'action' => 'backup_deleted',
                'description' => "Deleted database backup $id",
                'ip_address' => request()->ip(),
                'user_agent' => request()->userAgent(),
            ]);
        }
        return redirect()->back()->with('success', 'Backup deleted deleted.');
    }
}
